### ISSUE TITLE
Create a docker image for the backend

### ISSUE THREAD

**Issue by freddy33** [freddy33/qsm-go#13]
The backend executable should be launch in a container alongside postgresql container. For now let's use our own Kinto environment to run theses 2 services connected.
May be a local version with Docker compose can be useful for local tests?
For resolution and deployment of base images we could use the registry at fredsimon.jfrog.io .

**Comment by edwardkcyu** [comment]
Finished in https://github.com/freddy33/qsm-go/pull/18
