### ISSUE TITLE
Path Context render page

### ISSUE THREAD

**Issue by freddy33** [freddy33/qsm-go#35]
The rendering using three.js of the selected path nodes.
The left form and selection fields on the side should have:

- [x] Editable path context id from the list of existing path context ids),
- [x] Read only fields:  growth type, growth index, growth offset
- [x] Read only field max distance + a button to synchronously ask for only +1
- [x] Editable fields: From (need to be below or equal to max dist), To (need to be below or equal to max dist), Delta (0-maxdist)
- [x] Render button

The rendering canvas should be able to:
- [x] Start/Stop rotation
- [x] Zoom in/out (always keep center (0,0,0) in canvas center)
- [x] Good rendering speed

**Comment by edwardkcyu** [comment]
some more UI changes

### Path Context List
- [x] add Type, Index, Offset as columns
- [x] order by columns
- [x] default: growth type 8

### Render Page
- [x] a +1 button on the render to increase from and to by one in one click and render. 
- [x] to change the color of all the points where (p.x % 3 + p.y % 3 + p.z % 3) == 0 (It's the main points) or even to filter for them only.
