### ISSUE TITLE
Render nodes inside a space

### ISSUE THREAD

**Issue by edwardkcyu** [freddy33/qsm-go#66]
Create a page to do the space rendering.
To start with, this page should
- [x] Add a `Render` button in the `Actions` column of the Space page
- [x] Add a `Render` button to event list page
- [x] Render the nodes only in the render page. API: `GET /space-time`. Use `response.filtered_nodes` for rendering.
- [x] `+1` button for `current_time`

**Comment by freddy33** [comment]
The `Render` button should also be in the event list page.
The `GET /space-time` takes the space id (selected when clicking on the render button) and the current time which a positive integer. The current time should be a field with +1 action.
